'use client'
import { createContext, useContext, useEffect, useState, ReactNode } from 'react'

export type Lang = 'en' | 'hi' | 'mr' | 'bn' | 'ur' | 'te'

export const LANGUAGES: { code: Lang; label: string; native: string; dir?: 'rtl' }[] = [
  { code: 'en', label: 'English',  native: 'English'  },
  { code: 'hi', label: 'Hindi',    native: 'हिंदी'     },
  { code: 'mr', label: 'Marathi',  native: 'मराठी'    },
  { code: 'bn', label: 'Bengali',  native: 'বাংলা'    },
  { code: 'ur', label: 'Urdu',     native: 'اردو',    dir: 'rtl' },
  { code: 'te', label: 'Telugu',   native: 'తెలుగు'   },
]

/* ── Translations ──────────────────────────────────────────────── */
export const T = {
  en: {
    greeting_morning:   'Good morning',
    greeting_afternoon: 'Good afternoon',
    greeting_evening:   'Good evening',
    today_money:        "Today's Money",
    this_week:          'This week',
    go_online:          'Start Working — Go Online',
    you_are_online:     'You are online. Jobs can find you now.',
    jobs_near_you:      'Jobs Near You',
    see_all:            'See all',
    view_apply:         'View details & Apply',
    filters:            ['All','Today','Tomorrow','Near Me','High Pay'],
    you_earn:           'you earn',
    spots_left:         (n:number) => `${n} spot${n!==1?'s':''} left`,
    urgent:             '⚡ Urgent',
    apply_btn:          'Apply for This Job →',
    applied_btn:        'Done! You applied',
    home:               'Home',
    browse:             'Browse',
    shifts:             'Shifts',
    earnings:           'Earnings',
    profile:            'Profile',
    total_earned:       'Total Earned (This Month)',
    in_your_bank:       'In your bank',
    on_the_way:         'On the way',
    this_week_lbl:      'This Week',
    payment_history:    'Payment History',
    paid_lbl:           '✓ Paid',
    processing_lbl:     '⏳ Processing',
    my_shifts:          'My Shifts',
    upcoming:           '📅 Upcoming',
    past_shifts:        '✅ Past',
    my_availability:    'My Availability',
    tap_to_show:        'Tap to show when you can work',
    avail_set:          (n:number) => `${n} slots set`,
    available:          'Available',
    not_available:      'Not available',
    settings:           'Settings',
    notifications_lbl:  'Notifications',
    all_lbl:            'All',
    unread_lbl:         'Unread',
    no_notifs:          'No notifications yet',
    confirm_job_ttl:    'Job Accepted!',
    confirm_job_sub:    'Well done! Your shift is confirmed.',
    get_directions:     'Get Directions',
    tell_friend:        'Tell a Friend',
    back_to_jobs:       'Back to Jobs',
    slide_to_accept:    'Slide to accept →',
    urgent_nearby:      'URGENT NEARBY',
    urgent_headline:    'Employer needs someone right now — within 1 hour',
    urgent_spots_txt:   (dist:string, n:number) => `${dist} from you · Only ${n} spot${n!==1?'s':''} left`,
    accept_job:         'Accept This Job',
    accept_job_sub:     'View full details before confirming',
    not_interested:     'Not interested',
    enter_arrival_otp:  'Enter Arrival OTP',
    ask_employer_otp:   'Ask your employer for the 6-digit code',
    starts_shift_timer: 'This starts your shift timer',
    confirm_arrival:    'Confirm Arrival',
    shift_in_progress:  'Shift in progress',
    earned_so_far:      'Earned so far',
    slide_to_end:       'Slide to End Shift',
    slide_to_end_sub:   'Slide to mark shift as complete',
    shift_ended:        'Shift Ended!',
    accepted_lbl:       'Accepted!',
    active_shift:       'Active Shift',
    confirm_arrival_ttl:'Confirm Arrival',
    wrong_otp:          'Wrong OTP — try again',
    demo_otp:           'Demo OTP:',
    job_details:        'Job Details',
    what_to_bring:      'What to Bring',
    money_note:         'Money paid directly to your account after the shift',
    you_will_earn:      'You will earn',
    what_bring_items:   ['Valid ID card','Comfortable shoes','Water bottle','Your phone'],
    skills_title:       'My Skills',
    skills_sub:         'Select what kind of work you can do',
    edit_info:          'Edit Info',
    work_area:          'Work Area',
    languages_speak:    'Languages I Speak',
    save_changes:       'Save Changes',
    search_placeholder: 'Search jobs, companies...',
    no_jobs_found:      'No jobs found',
    no_jobs_sub:        'Try a different search or category',
    rate_job:           '⭐ Rate this job',
    confirmed:          'Confirmed',
    pending:            'Pending',
    completed:          'Completed',
    jobs_done:          'Jobs done',
    your_rating:        'Your rating',
    money_coming:       'Money coming',
    results:            'Results',
    all_jobs:           'All Jobs',
    date_when:          'When',
    duration:           'Duration',
    pay_lbl:            'Pay',
    distance:           'Distance',
    slots:              'Slots',
    rating:             'Rating',
    onb1_title:         'Find Work Near You',
    onb1_sub:           'See verified jobs within 5 km of your home. Choose shifts that fit your time.',
    onb2_title:         'Earn ₹99–₹129 Per Hour',
    onb2_sub:           'Fixed hourly rates. No agent cuts. No hidden fees. What you see is what you get.',
    onb3_title:         'Get Paid the Same Day',
    onb3_sub:           'Money goes straight to your bank account after every shift. No waiting.',
    onb4_title:         'Safe & Verified Jobs Only',
    onb4_sub:           'Every employer is checked. Every job is real. Your Aadhaar keeps you safe.',
    get_started:        'Get Started →',
    already_account:    'Already have an account? Login',
    login_title:        'Welcome back',
    login_sub:          'Enter your phone number to continue',
    phone_label:        'Phone Number',
    phone_placeholder:  'Enter 10-digit mobile number',
    password_label:     'Password',
    password_placeholder:'Enter your password',
    login_btn:          'Login',
    no_account:         "Don't have an account? Register",
    register_title:     'Create Account',
    register_sub:       'Join thousands of workers earning daily',
    name_label:         'Full Name',
    name_placeholder:   'Enter your full name',
    city_label:         'Your City',
    city_placeholder:   'e.g. Gurgaon, Delhi, Bangalore',
    lang_label:         'App Language',
    register_btn:       'Create Account',
    have_account:       'Already have an account? Login',
    choose_language:    'Choose Your Language',
    choose_language_sub:'Select the language you are most comfortable with',
    continue_btn:       'Continue',
    change_language:    'Change Language',

    // Rate-worker modal (auto-pops when employer's booking flips to COMPLETED)
    rate_worker_title:    'Rate the worker',
    rate_worker_sub:      'Your rating helps maintain quality on the platform',
    rate_stars_label:     'Tap the stars',
    rate_review_ph:       'Add a short review (optional)',
    rate_submit:          'Submit rating',
    rate_skip:            'Skip',
    rate_submitting:      'Submitting…',
    rate_thanks:          'Thanks for your feedback!',
    rate_failed:          'Could not submit. Try again.',

    // Cancel-refund (only available while shift is OPEN)
    cancel_shift_btn:     'Cancel & refund',
    cancel_shift_title:   'Cancel this booking?',
    cancel_shift_sub:     'You\'ll get a full refund. This is only available before a worker accepts.',
    cancel_shift_reason_ph:'Reason (optional)',
    cancel_shift_confirm: 'Yes, cancel & refund',
    cancel_shift_back:    'Keep booking',
    cancel_shift_done:    'Booking cancelled · Refund initiated',
    cancel_shift_failed:  'Could not cancel. Try again.',

    // Post-payment confirmation screen
    booked_title:         'Booking placed!',
    booked_sub:           'We\'re notifying nearby workers right now',
    booked_searching:     'Finding workers near you…',
    booked_view_job:      'View live status',

    // Reschedule (primary employer action while shift is OPEN)
    reschedule_btn:         'Reschedule',
    reschedule_title:       'Reschedule this booking',
    reschedule_sub:         'Pick a new date and start time. Your payment and any worker still searching will carry over.',
    reschedule_date_label:  'New date',
    reschedule_start_label: 'New start time',
    reschedule_end_label:   'New end time (optional)',
    reschedule_confirm:     'Save new schedule',
    reschedule_back:        'Keep current schedule',
    reschedule_submitting:  'Saving…',
    reschedule_done:        'Schedule updated',
    reschedule_failed:      'Could not reschedule. Try again.',
    reschedule_or_cancel:   'Or cancel & refund instead',
  },

  hi: {
    greeting_morning:   'सुप्रभात',
    greeting_afternoon: 'नमस्कार',
    greeting_evening:   'शुभ संध्या',
    today_money:        'आज की कमाई',
    this_week:          'इस हफ़्ते',
    go_online:          'काम शुरू करें — ऑनलाइन हों',
    you_are_online:     'आप ऑनलाइन हैं। अब नौकरी मिल सकती है।',
    jobs_near_you:      'आपके पास की नौकरियाँ',
    see_all:            'सब देखें',
    view_apply:         'विवरण देखें और आवेदन करें',
    filters:            ['सब','आज','कल','पास में','अधिक वेतन'],
    you_earn:           'आपको मिलेगा',
    spots_left:         (n:number) => `${n} जगह बची`,
    urgent:             '⚡ तुरंत चाहिए',
    apply_btn:          'इस काम के लिए आवेदन करें →',
    applied_btn:        'हो गया! आवेदन हो गया',
    home:               'होम',
    browse:             'ढूंढें',
    shifts:             'शिफ़्ट',
    earnings:           'कमाई',
    profile:            'प्रोफ़ाइल',
    total_earned:       'कुल कमाई (इस महीने)',
    in_your_bank:       'आपके बैंक में',
    on_the_way:         'आने वाला है',
    this_week_lbl:      'इस हफ़्ते',
    payment_history:    'भुगतान इतिहास',
    paid_lbl:           '✓ मिल गया',
    processing_lbl:     '⏳ आ रहा है',
    my_shifts:          'मेरी शिफ़्ट',
    upcoming:           '📅 आने वाली',
    past_shifts:        '✅ गुज़री हुई',
    my_availability:    'मेरी उपलब्धता',
    tap_to_show:        'टैप करें कि कब काम कर सकते हैं',
    avail_set:          (n:number) => `${n} स्लॉट सेट`,
    available:          'उपलब्ध',
    not_available:      'उपलब्ध नहीं',
    settings:           'सेटिंग्स',
    notifications_lbl:  'सूचनाएँ',
    all_lbl:            'सब',
    unread_lbl:         'नहीं पढ़ा',
    no_notifs:          'अभी कोई सूचना नहीं',
    confirm_job_ttl:    'नौकरी मिल गई!',
    confirm_job_sub:    'बहुत अच्छा! आपकी शिफ़्ट पक्की हो गई।',
    get_directions:     'रास्ता देखें',
    tell_friend:        'दोस्त को बताएँ',
    back_to_jobs:       'वापस नौकरियों पर',
    slide_to_accept:    'स्वीकार करने के लिए स्लाइड करें →',
    urgent_nearby:      'तुरंत पास में',
    urgent_headline:    'नियोक्ता को अभी किसी की ज़रूरत है — 1 घंटे में',
    urgent_spots_txt:   (dist:string, n:number) => `${dist} दूर · सिर्फ ${n} जगह बची`,
    accept_job:         'यह काम स्वीकार करें',
    accept_job_sub:     'पुष्टि से पहले पूरा विवरण देखें',
    not_interested:     'रुचि नहीं',
    enter_arrival_otp:  'आगमन OTP दर्ज करें',
    ask_employer_otp:   'नियोक्ता से 6-अंकों का कोड लें',
    starts_shift_timer: 'यह आपकी शिफ़्ट टाइमर शुरू करेगा',
    confirm_arrival:    'आगमन पुष्टि करें',
    shift_in_progress:  'शिफ़्ट चल रही है',
    earned_so_far:      'अब तक की कमाई',
    slide_to_end:       'शिफ़्ट समाप्त करने के लिए स्लाइड करें',
    slide_to_end_sub:   'शिफ़्ट पूरी करने के लिए स्लाइड करें',
    shift_ended:        'शिफ़्ट खत्म!',
    accepted_lbl:       'स्वीकृत!',
    active_shift:       'चालू शिफ़्ट',
    confirm_arrival_ttl:'आगमन पुष्टि',
    wrong_otp:          'गलत OTP — फिर से कोशिश करें',
    demo_otp:           'डेमो OTP:',
    job_details:        'काम की जानकारी',
    what_to_bring:      'क्या लाना है',
    money_note:         'शिफ़्ट के बाद पैसा सीधे आपके खाते में आएगा',
    you_will_earn:      'आपको मिलेगा',
    what_bring_items:   ['वैध पहचान पत्र','आरामदायक जूते','पानी की बोतल','आपका फ़ोन'],
    skills_title:       'मेरे कौशल',
    skills_sub:         'बताएँ कि आप क्या काम कर सकते हैं',
    edit_info:          'जानकारी बदलें',
    work_area:          'काम की जगह',
    languages_speak:    'मुझे आती है भाषा',
    save_changes:       'सेव करें',
    search_placeholder: 'नौकरी, कंपनी ढूंढें...',
    no_jobs_found:      'कोई नौकरी नहीं मिली',
    no_jobs_sub:        'अलग खोज या श्रेणी आज़माएँ',
    rate_job:           '⭐ इस काम को रेट करें',
    confirmed:          'पक्का',
    pending:            'बाकी है',
    completed:          'हो गया',
    jobs_done:          'काम किए',
    your_rating:        'आपकी रेटिंग',
    money_coming:       'पैसा आने वाला',
    results:            'परिणाम',
    all_jobs:           'सभी नौकरियाँ',
    date_when:          'कब',
    duration:           'कितना समय',
    pay_lbl:            'वेतन',
    distance:           'दूरी',
    slots:              'जगह',
    rating:             'रेटिंग',
    onb1_title:         'अपने पास काम ढूंढें',
    onb1_sub:           'घर से 5 किमी के अंदर सत्यापित काम देखें। अपने समय के अनुसार शिफ़्ट चुनें।',
    onb2_title:         '₹99–₹129 प्रति घंटा कमाएँ',
    onb2_sub:           'तय दर मिलेगी। कोई एजेंट कट नहीं। कोई छुपी फ़ीस नहीं।',
    onb3_title:         'उसी दिन पैसा मिलेगा',
    onb3_sub:           'हर शिफ़्ट के बाद पैसा सीधे बैंक में आएगा।',
    onb4_title:         'सुरक्षित और सत्यापित काम ही',
    onb4_sub:           'हर नियोक्ता जाँचा हुआ है। हर काम असली है।',
    get_started:        'शुरू करें →',
    already_account:    'पहले से खाता है? लॉगिन करें',
    login_title:        'वापस आए',
    login_sub:          'जारी रखने के लिए अपना नंबर दर्ज करें',
    phone_label:        'मोबाइल नंबर',
    phone_placeholder:  '10 अंकों का नंबर दर्ज करें',
    password_label:     'पासवर्ड',
    password_placeholder:'पासवर्ड दर्ज करें',
    login_btn:          'लॉगिन करें',
    no_account:         'खाता नहीं है? पंजीकरण करें',
    register_title:     'खाता बनाएँ',
    register_sub:       'हज़ारों श्रमिकों के साथ रोज़ाना कमाएँ',
    name_label:         'पूरा नाम',
    name_placeholder:   'अपना पूरा नाम लिखें',
    city_label:         'आपका शहर',
    city_placeholder:   'जैसे गुरुग्राम, दिल्ली, बेंगलुरु',
    lang_label:         'ऐप की भाषा',
    register_btn:       'खाता बनाएँ',
    have_account:       'पहले से खाता है? लॉगिन करें',
    choose_language:    'भाषा चुनें',
    choose_language_sub:'वह भाषा चुनें जो आपको सबसे अच्छी लगती है',
    continue_btn:       'आगे बढ़ें',
    change_language:    'भाषा बदलें',

    rate_worker_title:    'वर्कर को रेटिंग दें',
    rate_worker_sub:      'आपकी रेटिंग प्लेटफ़ॉर्म की गुणवत्ता बनाए रखने में मदद करती है',
    rate_stars_label:     'सितारे चुनें',
    rate_review_ph:       'छोटा रिव्यू लिखें (वैकल्पिक)',
    rate_submit:          'रेटिंग भेजें',
    rate_skip:            'छोड़ें',
    rate_submitting:      'भेज रहे हैं…',
    rate_thanks:          'आपकी राय के लिए धन्यवाद!',
    rate_failed:          'रेटिंग नहीं भेज पाए। फिर से कोशिश करें।',

    cancel_shift_btn:     'रद्द करें और रिफंड पाएँ',
    cancel_shift_title:   'क्या यह बुकिंग रद्द करनी है?',
    cancel_shift_sub:     'पूरा रिफंड मिलेगा। यह केवल वर्कर के स्वीकार करने से पहले ही उपलब्ध है।',
    cancel_shift_reason_ph:'कारण (वैकल्पिक)',
    cancel_shift_confirm: 'हाँ, रद्द करें और रिफंड दें',
    cancel_shift_back:    'बुकिंग रखें',
    cancel_shift_done:    'बुकिंग रद्द · रिफंड शुरू',
    cancel_shift_failed:  'रद्द नहीं हो पाया। फिर से कोशिश करें।',

    booked_title:         'बुकिंग हो गई!',
    booked_sub:           'हम अभी आस-पास के वर्कर्स को सूचना दे रहे हैं',
    booked_searching:     'पास के वर्कर्स ढूँढ रहे हैं…',
    booked_view_job:      'लाइव स्थिति देखें',

    reschedule_btn:         'समय बदलें',
    reschedule_title:       'बुकिंग का समय बदलें',
    reschedule_sub:         'नई तारीख और शुरू होने का समय चुनें। आपका पेमेंट और सर्च करता वर्कर वैसा ही रहेगा।',
    reschedule_date_label:  'नई तारीख',
    reschedule_start_label: 'नया शुरू समय',
    reschedule_end_label:   'नया अंत समय (वैकल्पिक)',
    reschedule_confirm:     'नया शेड्यूल सेव करें',
    reschedule_back:        'मौजूदा शेड्यूल रखें',
    reschedule_submitting:  'सेव कर रहे हैं…',
    reschedule_done:        'शेड्यूल अपडेट हो गया',
    reschedule_failed:      'समय नहीं बदल पाए। फिर से कोशिश करें।',
    reschedule_or_cancel:   'या रद्द करें और रिफंड पाएँ',
  },

  mr: {
    greeting_morning:   'शुभ सकाळ',
    greeting_afternoon: 'नमस्कार',
    greeting_evening:   'शुभ संध्याकाळ',
    today_money:        'आजची कमाई',
    this_week:          'या आठवड्यात',
    go_online:          'काम सुरू करा — ऑनलाईन व्हा',
    you_are_online:     'तुम्ही ऑनलाईन आहात. आता नोकरी मिळू शकते.',
    jobs_near_you:      'तुमच्या जवळच्या नोकऱ्या',
    see_all:            'सर्व पहा',
    view_apply:         'तपशील पहा आणि अर्ज करा',
    filters:            ['सर्व','आज','उद्या','जवळ','जास्त पगार'],
    you_earn:           'तुम्हाला मिळेल',
    spots_left:         (n:number) => `${n} जागा उरल्या`,
    urgent:             '⚡ तातडीचे',
    apply_btn:          'या कामासाठी अर्ज करा →',
    applied_btn:        'झाले! अर्ज केला',
    home:               'होम',
    browse:             'शोधा',
    shifts:             'शिफ्ट',
    earnings:           'कमाई',
    profile:            'प्रोफाईल',
    total_earned:       'एकूण कमाई (या महिन्यात)',
    in_your_bank:       'तुमच्या बँकेत',
    on_the_way:         'येत आहे',
    this_week_lbl:      'या आठवड्यात',
    payment_history:    'पेमेंट इतिहास',
    paid_lbl:           '✓ मिळाले',
    processing_lbl:     '⏳ येत आहे',
    my_shifts:          'माझ्या शिफ्ट',
    upcoming:           '📅 येणाऱ्या',
    past_shifts:        '✅ गेलेल्या',
    my_availability:    'माझी उपलब्धता',
    tap_to_show:        'कधी काम करू शकता ते टॅप करा',
    avail_set:          (n:number) => `${n} स्लॉट सेट`,
    available:          'उपलब्ध',
    not_available:      'उपलब्ध नाही',
    settings:           'सेटिंग्ज',
    notifications_lbl:  'सूचना',
    all_lbl:            'सर्व',
    unread_lbl:         'न वाचलेले',
    no_notifs:          'अजून कोणतीही सूचना नाही',
    confirm_job_ttl:    'नोकरी मिळाली!',
    confirm_job_sub:    'शाब्बास! तुमची शिफ्ट पक्की झाली.',
    get_directions:     'दिशा पहा',
    tell_friend:        'मित्राला सांगा',
    back_to_jobs:       'नोकऱ्यांकडे परत',
    slide_to_accept:    'स्वीकारण्यासाठी स्लाइड करा →',
    urgent_nearby:      'जवळ तातडीचे',
    urgent_headline:    'नियोक्त्याला आत्ता कोणाची गरज आहे — 1 तासात',
    urgent_spots_txt:   (dist:string, n:number) => `${dist} दूर · फक्त ${n} जागा उरल्या`,
    accept_job:         'हे काम स्वीकारा',
    accept_job_sub:     'पुष्टी करण्यापूर्वी संपूर्ण तपशील पहा',
    not_interested:     'रुची नाही',
    enter_arrival_otp:  'आगमन OTP टाका',
    ask_employer_otp:   'नियोक्त्याकडून 6-अंकी कोड घ्या',
    starts_shift_timer: 'हे तुमचे शिफ्ट टाइमर सुरू करेल',
    confirm_arrival:    'आगमन पुष्टी करा',
    shift_in_progress:  'शिफ्ट सुरू आहे',
    earned_so_far:      'आतापर्यंतची कमाई',
    slide_to_end:       'शिफ्ट संपवण्यासाठी स्लाइड करा',
    slide_to_end_sub:   'शिफ्ट पूर्ण करण्यासाठी स्लाइड करा',
    shift_ended:        'शिफ्ट संपली!',
    accepted_lbl:       'स्वीकृत!',
    active_shift:       'सुरू असलेली शिफ्ट',
    confirm_arrival_ttl:'आगमन पुष्टी',
    wrong_otp:          'चुकीचा OTP — पुन्हा प्रयत्न करा',
    demo_otp:           'डेमो OTP:',
    job_details:        'कामाची माहिती',
    what_to_bring:      'काय आणायचे',
    money_note:         'शिफ्टनंतर पैसे थेट तुमच्या खात्यात येतील',
    you_will_earn:      'तुम्हाला मिळेल',
    what_bring_items:   ['वैध ओळखपत्र','आरामदायक शूज','पाण्याची बाटली','तुमचा फोन'],
    skills_title:       'माझ्या कौशल्ये',
    skills_sub:         'तुम्ही कोणते काम करू शकता ते सांगा',
    edit_info:          'माहिती बदला',
    work_area:          'काम करण्याची जागा',
    languages_speak:    'मला येणाऱ्या भाषा',
    save_changes:       'सेव्ह करा',
    search_placeholder: 'नोकरी, कंपनी शोधा...',
    no_jobs_found:      'कोणतीही नोकरी सापडली नाही',
    no_jobs_sub:        'वेगळी शोध किंवा श्रेणी वापरा',
    rate_job:           '⭐ या कामाला रेट करा',
    confirmed:          'पक्के',
    pending:            'बाकी आहे',
    completed:          'झाले',
    jobs_done:          'काम केले',
    your_rating:        'तुमची रेटिंग',
    money_coming:       'पैसे येत आहेत',
    results:            'निकाल',
    all_jobs:           'सर्व नोकऱ्या',
    date_when:          'कधी',
    duration:           'किती वेळ',
    pay_lbl:            'पगार',
    distance:           'अंतर',
    slots:              'जागा',
    rating:             'रेटिंग',
    onb1_title:         'जवळ काम शोधा',
    onb1_sub:           'घरापासून 5 किमीत सत्यापित काम पहा. तुमच्या वेळेनुसार शिफ्ट निवडा.',
    onb2_title:         '₹99–₹129 प्रति तास कमवा',
    onb2_sub:           'निश्चित दर. कोणताही एजंट कट नाही. कोणती लपलेली फी नाही.',
    onb3_title:         'त्याच दिवशी पैसे मिळतील',
    onb3_sub:           'प्रत्येक शिफ्टनंतर पैसे थेट बँकेत जातात.',
    onb4_title:         'सुरक्षित आणि सत्यापित काम',
    onb4_sub:           'प्रत्येक नियोक्ता तपासलेला आहे. आधारने सुरक्षा.',
    get_started:        'सुरू करा →',
    already_account:    'आधीच खाते आहे? लॉगिन करा',
    login_title:        'परत आलात',
    login_sub:          'सुरू ठेवण्यासाठी नंबर टाका',
    phone_label:        'मोबाईल नंबर',
    phone_placeholder:  '10 अंकी नंबर टाका',
    password_label:     'पासवर्ड',
    password_placeholder:'पासवर्ड टाका',
    login_btn:          'लॉगिन करा',
    no_account:         'खाते नाही? नोंदणी करा',
    register_title:     'खाते बनवा',
    register_sub:       'हजारो कामगारांसोबत रोज कमवा',
    name_label:         'पूर्ण नाव',
    name_placeholder:   'तुमचे पूर्ण नाव लिहा',
    city_label:         'तुमचे शहर',
    city_placeholder:   'उदा. गुरुग्राम, पुणे, नागपूर',
    lang_label:         'ॲपची भाषा',
    register_btn:       'खाते बनवा',
    have_account:       'आधीच खाते आहे? लॉगिन करा',
    choose_language:    'भाषा निवडा',
    choose_language_sub:'तुम्हाला सर्वात सोयीस्कर भाषा निवडा',
    continue_btn:       'पुढे जा',
    change_language:    'भाषा बदला',

    rate_worker_title:    'वर्करला रेटिंग द्या',
    rate_worker_sub:      'तुमची रेटिंग प्लॅटफॉर्मची गुणवत्ता राखण्यात मदत करते',
    rate_stars_label:     'तारे निवडा',
    rate_review_ph:       'छोटा रिव्ह्यू लिहा (वैकल्पिक)',
    rate_submit:          'रेटिंग पाठवा',
    rate_skip:            'वगळा',
    rate_submitting:      'पाठवत आहोत…',
    rate_thanks:          'तुमच्या अभिप्रायाबद्दल धन्यवाद!',
    rate_failed:          'रेटिंग पाठवू शकलो नाही. पुन्हा प्रयत्न करा.',

    cancel_shift_btn:     'रद्द करा आणि रिफंड घ्या',
    cancel_shift_title:   'ही बुकिंग रद्द करायची?',
    cancel_shift_sub:     'संपूर्ण रिफंड मिळेल. हे फक्त वर्कर स्वीकारण्यापूर्वी उपलब्ध आहे.',
    cancel_shift_reason_ph:'कारण (वैकल्पिक)',
    cancel_shift_confirm: 'होय, रद्द करा आणि रिफंड द्या',
    cancel_shift_back:    'बुकिंग ठेवा',
    cancel_shift_done:    'बुकिंग रद्द · रिफंड सुरू',
    cancel_shift_failed:  'रद्द होऊ शकले नाही. पुन्हा प्रयत्न करा.',

    booked_title:         'बुकिंग झाली!',
    booked_sub:           'आम्ही जवळच्या वर्कर्सना सूचना देत आहोत',
    booked_searching:     'जवळचे वर्कर्स शोधत आहोत…',
    booked_view_job:      'लाईव्ह स्थिती पहा',

    reschedule_btn:         'वेळ बदला',
    reschedule_title:       'बुकिंगचा वेळ बदला',
    reschedule_sub:         'नवीन तारीख आणि सुरू होण्याची वेळ निवडा. तुमचे पेमेंट आणि शोधत असलेला वर्कर तसाच राहील.',
    reschedule_date_label:  'नवीन तारीख',
    reschedule_start_label: 'नवीन सुरू वेळ',
    reschedule_end_label:   'नवीन अंत वेळ (वैकल्पिक)',
    reschedule_confirm:     'नवीन शेड्यूल सेव्ह करा',
    reschedule_back:        'सध्याचा शेड्यूल ठेवा',
    reschedule_submitting:  'सेव्ह करत आहोत…',
    reschedule_done:        'शेड्यूल अपडेट झाले',
    reschedule_failed:      'वेळ बदलू शकलो नाही. पुन्हा प्रयत्न करा.',
    reschedule_or_cancel:   'किंवा रद्द करा आणि रिफंड घ्या',
  },

  bn: {
    greeting_morning:   'সুপ্রভাত',
    greeting_afternoon: 'নমস্কার',
    greeting_evening:   'শুভ সন্ধ্যা',
    today_money:        'আজকের আয়',
    this_week:          'এই সপ্তাহে',
    go_online:          'কাজ শুরু করুন — অনলাইন হন',
    you_are_online:     'আপনি অনলাইন আছেন। এখন কাজ পেতে পারেন।',
    jobs_near_you:      'আপনার কাছের কাজ',
    see_all:            'সব দেখুন',
    view_apply:         'বিস্তারিত দেখুন ও আবেদন করুন',
    filters:            ['সব','আজ','কাল','কাছে','বেশি বেতন'],
    you_earn:           'আপনি পাবেন',
    spots_left:         (n:number) => `${n}টি জায়গা বাকি`,
    urgent:             '⚡ জরুরি',
    apply_btn:          'এই কাজে আবেদন করুন →',
    applied_btn:        'হয়ে গেছে! আবেদন করা হয়েছে',
    home:               'হোম',
    browse:             'খুঁজুন',
    shifts:             'শিফট',
    earnings:           'আয়',
    profile:            'প্রোফাইল',
    total_earned:       'মোট আয় (এই মাসে)',
    in_your_bank:       'আপনার ব্যাংকে',
    on_the_way:         'আসছে',
    this_week_lbl:      'এই সপ্তাহে',
    payment_history:    'পেমেন্ট ইতিহাস',
    paid_lbl:           '✓ পেয়েছি',
    processing_lbl:     '⏳ আসছে',
    my_shifts:          'আমার শিফট',
    upcoming:           '📅 আসন্ন',
    past_shifts:        '✅ আগের',
    my_availability:    'আমার প্রাপ্যতা',
    tap_to_show:        'কখন কাজ করতে পারবেন ট্যাপ করুন',
    avail_set:          (n:number) => `${n}টি স্লট সেট`,
    available:          'উপলব্ধ',
    not_available:      'উপলব্ধ নয়',
    settings:           'সেটিংস',
    notifications_lbl:  'বিজ্ঞপ্তি',
    all_lbl:            'সব',
    unread_lbl:         'অপঠিত',
    no_notifs:          'এখনো কোনো বিজ্ঞপ্তি নেই',
    confirm_job_ttl:    'কাজ পেয়েছেন!',
    confirm_job_sub:    'দারুণ! আপনার শিফট নিশ্চিত হয়েছে।',
    get_directions:     'দিকনির্দেশনা দেখুন',
    tell_friend:        'বন্ধুকে বলুন',
    back_to_jobs:       'কাজে ফিরে যান',
    slide_to_accept:    'গ্রহণ করতে স্লাইড করুন →',
    urgent_nearby:      'কাছে জরুরি',
    urgent_headline:    'নিয়োগকর্তার এখনই কারো দরকার — ১ ঘণ্টার মধ্যে',
    urgent_spots_txt:   (dist:string, n:number) => `${dist} দূরে · মাত্র ${n}টি জায়গা বাকি`,
    accept_job:         'এই কাজ গ্রহণ করুন',
    accept_job_sub:     'নিশ্চিত করার আগে সম্পূর্ণ বিবরণ দেখুন',
    not_interested:     'আগ্রহ নেই',
    enter_arrival_otp:  'আগমন OTP দিন',
    ask_employer_otp:   'নিয়োগকর্তার কাছ থেকে ৬ সংখ্যার কোড নিন',
    starts_shift_timer: 'এটি আপনার শিফট টাইমার শুরু করবে',
    confirm_arrival:    'আগমন নিশ্চিত করুন',
    shift_in_progress:  'শিফট চলছে',
    earned_so_far:      'এখন পর্যন্ত আয়',
    slide_to_end:       'শিফট শেষ করতে স্লাইড করুন',
    slide_to_end_sub:   'শিফট সম্পন্ন করতে স্লাইড করুন',
    shift_ended:        'শিফট শেষ!',
    accepted_lbl:       'গৃহীত!',
    active_shift:       'চলমান শিফট',
    confirm_arrival_ttl:'আগমন নিশ্চিতকরণ',
    wrong_otp:          'ভুল OTP — আবার চেষ্টা করুন',
    demo_otp:           'ডেমো OTP:',
    job_details:        'কাজের বিবরণ',
    what_to_bring:      'কী আনবেন',
    money_note:         'শিফটের পরে সরাসরি আপনার অ্যাকাউন্টে টাকা যাবে',
    you_will_earn:      'আপনি পাবেন',
    what_bring_items:   ['বৈধ পরিচয়পত্র','আরামদায়ক জুতো','পানির বোতল','আপনার ফোন'],
    skills_title:       'আমার দক্ষতা',
    skills_sub:         'আপনি কী কাজ করতে পারেন তা বলুন',
    edit_info:          'তথ্য পরিবর্তন করুন',
    work_area:          'কাজের এলাকা',
    languages_speak:    'আমি যে ভাষা বলি',
    save_changes:       'সেভ করুন',
    search_placeholder: 'কাজ, কোম্পানি খুঁজুন...',
    no_jobs_found:      'কোনো কাজ পাওয়া যায়নি',
    no_jobs_sub:        'অন্য অনুসন্ধান বা বিভাগ চেষ্টা করুন',
    rate_job:           '⭐ এই কাজ রেট করুন',
    confirmed:          'নিশ্চিত',
    pending:            'বাকি আছে',
    completed:          'সম্পন্ন',
    jobs_done:          'কাজ করেছি',
    your_rating:        'আপনার রেটিং',
    money_coming:       'টাকা আসছে',
    results:            'ফলাফল',
    all_jobs:           'সব কাজ',
    date_when:          'কখন',
    duration:           'কতক্ষণ',
    pay_lbl:            'বেতন',
    distance:           'দূরত্ব',
    slots:              'জায়গা',
    rating:             'রেটিং',
    onb1_title:         'কাছে কাজ খুঁজুন',
    onb1_sub:           'বাড়ি থেকে ৫ কিমির মধ্যে যাচাইকৃত কাজ দেখুন।',
    onb2_title:         '₹৯৯–₹১২৯ প্রতি ঘণ্টা আয় করুন',
    onb2_sub:           'নির্ধারিত হার। কোনো এজেন্ট কাট নেই। কোনো লুকানো ফি নেই।',
    onb3_title:         'একই দিনে টাকা পাবেন',
    onb3_sub:           'প্রতিটি শিফটের পরে সরাসরি ব্যাংকে টাকা যাবে।',
    onb4_title:         'নিরাপদ ও যাচাইকৃত কাজ',
    onb4_sub:           'প্রতিটি নিয়োগকর্তা পরীক্ষিত। আধার দিয়ে সুরক্ষা।',
    get_started:        'শুরু করুন →',
    already_account:    'ইতিমধ্যে অ্যাকাউন্ট আছে? লগইন করুন',
    login_title:        'আবার স্বাগতম',
    login_sub:          'চালিয়ে যেতে আপনার নম্বর দিন',
    phone_label:        'মোবাইল নম্বর',
    phone_placeholder:  '১০ সংখ্যার নম্বর দিন',
    password_label:     'পাসওয়ার্ড',
    password_placeholder:'পাসওয়ার্ড দিন',
    login_btn:          'লগইন করুন',
    no_account:         'অ্যাকাউন্ট নেই? নিবন্ধন করুন',
    register_title:     'অ্যাকাউন্ট তৈরি করুন',
    register_sub:       'হাজারো কর্মীর সাথে প্রতিদিন আয় করুন',
    name_label:         'পূর্ণ নাম',
    name_placeholder:   'আপনার পূর্ণ নাম লিখুন',
    city_label:         'আপনার শহর',
    city_placeholder:   'যেমন গুরুগ্রাম, দিল্লি, কলকাতা',
    lang_label:         'অ্যাপের ভাষা',
    register_btn:       'অ্যাকাউন্ট তৈরি করুন',
    have_account:       'ইতিমধ্যে অ্যাকাউন্ট আছে? লগইন করুন',
    choose_language:    'ভাষা বেছে নিন',
    choose_language_sub:'আপনার সবচেয়ে সুবিধাজনক ভাষা বেছে নিন',
    continue_btn:       'এগিয়ে যান',
    change_language:    'ভাষা পরিবর্তন করুন',

    rate_worker_title:    'ওয়ার্কারকে রেটিং দিন',
    rate_worker_sub:      'আপনার রেটিং প্ল্যাটফর্মের গুণমান বজায় রাখতে সাহায্য করে',
    rate_stars_label:     'তারা বেছে নিন',
    rate_review_ph:       'ছোট রিভিউ লিখুন (ঐচ্ছিক)',
    rate_submit:          'রেটিং পাঠান',
    rate_skip:            'এড়িয়ে যান',
    rate_submitting:      'পাঠানো হচ্ছে…',
    rate_thanks:          'আপনার মতামতের জন্য ধন্যবাদ!',
    rate_failed:          'পাঠানো যায়নি। আবার চেষ্টা করুন।',

    cancel_shift_btn:     'বাতিল করে রিফান্ড নিন',
    cancel_shift_title:   'এই বুকিং বাতিল করবেন?',
    cancel_shift_sub:     'পুরো রিফান্ড পাবেন। ওয়ার্কার গ্রহণ করার আগেই কেবল উপলব্ধ।',
    cancel_shift_reason_ph:'কারণ (ঐচ্ছিক)',
    cancel_shift_confirm: 'হ্যাঁ, বাতিল করে রিফান্ড দিন',
    cancel_shift_back:    'বুকিং রাখুন',
    cancel_shift_done:    'বুকিং বাতিল · রিফান্ড শুরু',
    cancel_shift_failed:  'বাতিল হয়নি। আবার চেষ্টা করুন।',

    booked_title:         'বুকিং সম্পন্ন!',
    booked_sub:           'আমরা কাছের ওয়ার্কারদের জানাচ্ছি',
    booked_searching:     'কাছের ওয়ার্কার খোঁজা হচ্ছে…',
    booked_view_job:      'লাইভ স্ট্যাটাস দেখুন',

    reschedule_btn:         'সময় বদলান',
    reschedule_title:       'বুকিংয়ের সময় বদলান',
    reschedule_sub:         'নতুন তারিখ এবং শুরুর সময় বেছে নিন। আপনার পেমেন্ট এবং খোঁজা ওয়ার্কার বহাল থাকবে।',
    reschedule_date_label:  'নতুন তারিখ',
    reschedule_start_label: 'নতুন শুরুর সময়',
    reschedule_end_label:   'নতুন শেষ সময় (ঐচ্ছিক)',
    reschedule_confirm:     'নতুন সময়সূচি সংরক্ষণ করুন',
    reschedule_back:        'বর্তমান সময়সূচি রাখুন',
    reschedule_submitting:  'সংরক্ষণ হচ্ছে…',
    reschedule_done:        'সময়সূচি আপডেট হয়েছে',
    reschedule_failed:      'বদলানো যায়নি। আবার চেষ্টা করুন।',
    reschedule_or_cancel:   'অথবা বাতিল করে রিফান্ড নিন',
  },

  ur: {
    greeting_morning:   'صبح بخیر',
    greeting_afternoon: 'السلام علیکم',
    greeting_evening:   'شام بخیر',
    today_money:        'آج کی کمائی',
    this_week:          'اس ہفتے',
    go_online:          'کام شروع کریں — آن لائن ہوں',
    you_are_online:     'آپ آن لائن ہیں۔ اب نوکری مل سکتی ہے۔',
    jobs_near_you:      'آپ کے قریب نوکریاں',
    see_all:            'سب دیکھیں',
    view_apply:         'تفصیل دیکھیں اور درخواست دیں',
    filters:            ['سب','آج','کل','قریب','زیادہ تنخواہ'],
    you_earn:           'آپ کو ملے گا',
    spots_left:         (n:number) => `${n} جگہ باقی`,
    urgent:             '⚡ فوری',
    apply_btn:          'اس کام کے لیے درخواست دیں →',
    applied_btn:        'ہو گیا! درخواست دے دی',
    home:               'ہوم',
    browse:             'تلاش کریں',
    shifts:             'شفٹ',
    earnings:           'کمائی',
    profile:            'پروفائل',
    total_earned:       'کل کمائی (اس مہینے)',
    in_your_bank:       'آپ کے بینک میں',
    on_the_way:         'آ رہا ہے',
    this_week_lbl:      'اس ہفتے',
    payment_history:    'ادائیگی کی تاریخ',
    paid_lbl:           '✓ مل گیا',
    processing_lbl:     '⏳ آ رہا ہے',
    my_shifts:          'میری شفٹیں',
    upcoming:           '📅 آنے والی',
    past_shifts:        '✅ گزری ہوئی',
    my_availability:    'میری دستیابی',
    tap_to_show:        'ٹیپ کریں کہ کب کام کر سکتے ہیں',
    avail_set:          (n:number) => `${n} سلاٹ سیٹ`,
    available:          'دستیاب',
    not_available:      'دستیاب نہیں',
    settings:           'ترتیبات',
    notifications_lbl:  'اطلاعات',
    all_lbl:            'سب',
    unread_lbl:         'نہ پڑھا',
    no_notifs:          'ابھی کوئی اطلاع نہیں',
    confirm_job_ttl:    'نوکری مل گئی!',
    confirm_job_sub:    'شاباش! آپ کی شفٹ پکی ہو گئی۔',
    get_directions:     'راستہ دیکھیں',
    tell_friend:        'دوست کو بتائیں',
    back_to_jobs:       'نوکریوں پر واپس',
    slide_to_accept:    'قبول کرنے کے لیے سلائیڈ کریں →',
    urgent_nearby:      'قریب فوری',
    urgent_headline:    'مالک کو ابھی کسی کی ضرورت ہے — 1 گھنٹے میں',
    urgent_spots_txt:   (dist:string, n:number) => `${dist} دور · صرف ${n} جگہ باقی`,
    accept_job:         'یہ کام قبول کریں',
    accept_job_sub:     'تصدیق سے پہلے پوری تفصیل دیکھیں',
    not_interested:     'دلچسپی نہیں',
    enter_arrival_otp:  'آمد OTP درج کریں',
    ask_employer_otp:   'مالک سے 6 ہندسوں کا کوڈ لیں',
    starts_shift_timer: 'یہ آپ کا شفٹ ٹائمر شروع کرے گا',
    confirm_arrival:    'آمد کی تصدیق کریں',
    shift_in_progress:  'شفٹ جاری ہے',
    earned_so_far:      'ابھی تک کی کمائی',
    slide_to_end:       'شفٹ ختم کرنے کے لیے سلائیڈ کریں',
    slide_to_end_sub:   'شفٹ مکمل کرنے کے لیے سلائیڈ کریں',
    shift_ended:        'شفٹ ختم!',
    accepted_lbl:       'قبول!',
    active_shift:       'چالو شفٹ',
    confirm_arrival_ttl:'آمد کی تصدیق',
    wrong_otp:          'غلط OTP — دوبارہ کوشش کریں',
    demo_otp:           'ڈیمو OTP:',
    job_details:        'کام کی تفصیل',
    what_to_bring:      'کیا لانا ہے',
    money_note:         'شفٹ کے بعد پیسے سیدھے آپ کے کھاتے میں آئیں گے',
    you_will_earn:      'آپ کو ملے گا',
    what_bring_items:   ['درست شناختی کارڈ','آرام دہ جوتے','پانی کی بوتل','آپ کا فون'],
    skills_title:       'میری مہارتیں',
    skills_sub:         'بتائیں کہ آپ کیا کام کر سکتے ہیں',
    edit_info:          'معلومات بدلیں',
    work_area:          'کام کی جگہ',
    languages_speak:    'میری زبانیں',
    save_changes:       'محفوظ کریں',
    search_placeholder: 'نوکری، کمپنی تلاش کریں...',
    no_jobs_found:      'کوئی نوکری نہیں ملی',
    no_jobs_sub:        'مختلف تلاش یا زمرہ آزمائیں',
    rate_job:           '⭐ اس کام کو ریٹ کریں',
    confirmed:          'پکا',
    pending:            'باقی ہے',
    completed:          'مکمل',
    jobs_done:          'کام کیے',
    your_rating:        'آپ کی ریٹنگ',
    money_coming:       'پیسہ آ رہا ہے',
    results:            'نتائج',
    all_jobs:           'تمام نوکریاں',
    date_when:          'کب',
    duration:           'کتنا وقت',
    pay_lbl:            'تنخواہ',
    distance:           'فاصلہ',
    slots:              'جگہ',
    rating:             'ریٹنگ',
    onb1_title:         'قریب کام تلاش کریں',
    onb1_sub:           'گھر سے 5 کلومیٹر میں تصدیق شدہ کام دیکھیں۔',
    onb2_title:         '₹99–₹129 فی گھنٹہ کمائیں',
    onb2_sub:           'مقررہ اجرت۔ کوئی ایجنٹ کٹ نہیں۔ کوئی چھپی فیس نہیں۔',
    onb3_title:         'اسی دن پیسے ملیں گے',
    onb3_sub:           'ہر شفٹ کے بعد پیسے سیدھے بینک میں جائیں گے۔',
    onb4_title:         'محفوظ اور تصدیق شدہ کام',
    onb4_sub:           'ہر مالک جانچا ہوا ہے۔ آدھار سے تحفظ۔',
    get_started:        'شروع کریں →',
    already_account:    'پہلے سے کھاتہ ہے؟ لاگ ان کریں',
    login_title:        'واپس آئے',
    login_sub:          'جاری رکھنے کے لیے اپنا نمبر درج کریں',
    phone_label:        'موبائل نمبر',
    phone_placeholder:  '10 ہندسوں کا نمبر درج کریں',
    password_label:     'پاسورڈ',
    password_placeholder:'پاسورڈ درج کریں',
    login_btn:          'لاگ ان کریں',
    no_account:         'کھاتہ نہیں؟ رجسٹر کریں',
    register_title:     'کھاتہ بنائیں',
    register_sub:       'ہزاروں مزدوروں کے ساتھ روزانہ کمائیں',
    name_label:         'پورا نام',
    name_placeholder:   'اپنا پورا نام لکھیں',
    city_label:         'آپ کا شہر',
    city_placeholder:   'مثلاً ممبئی، دہلی، حیدرآباد',
    lang_label:         'ایپ کی زبان',
    register_btn:       'کھاتہ بنائیں',
    have_account:       'پہلے سے کھاتہ ہے؟ لاگ ان کریں',
    choose_language:    'زبان منتخب کریں',
    choose_language_sub:'وہ زبان منتخب کریں جو آپ کو سب سے آرام دہ ہو',
    continue_btn:       'آگے بڑھیں',
    change_language:    'زبان بدلیں',

    rate_worker_title:    'ورکر کو ریٹنگ دیں',
    rate_worker_sub:      'آپ کی ریٹنگ پلیٹ فارم کی کوالٹی برقرار رکھنے میں مدد کرتی ہے',
    rate_stars_label:     'ستارے منتخب کریں',
    rate_review_ph:       'مختصر تبصرہ لکھیں (اختیاری)',
    rate_submit:          'ریٹنگ بھیجیں',
    rate_skip:            'چھوڑیں',
    rate_submitting:      'بھیجا جا رہا ہے…',
    rate_thanks:          'آپ کی رائے کا شکریہ!',
    rate_failed:          'بھیج نہیں سکے۔ دوبارہ کوشش کریں۔',

    cancel_shift_btn:     'منسوخ کریں اور ریفنڈ پائیں',
    cancel_shift_title:   'یہ بکنگ منسوخ کرنا چاہتے ہیں؟',
    cancel_shift_sub:     'پورا ریفنڈ ملے گا۔ یہ صرف ورکر کے قبول کرنے سے پہلے دستیاب ہے۔',
    cancel_shift_reason_ph:'وجہ (اختیاری)',
    cancel_shift_confirm: 'ہاں، منسوخ کریں اور ریفنڈ دیں',
    cancel_shift_back:    'بکنگ رکھیں',
    cancel_shift_done:    'بکنگ منسوخ · ریفنڈ شروع',
    cancel_shift_failed:  'منسوخ نہیں ہو سکا۔ دوبارہ کوشش کریں۔',

    booked_title:         'بکنگ ہو گئی!',
    booked_sub:           'ہم قریبی ورکرز کو مطلع کر رہے ہیں',
    booked_searching:     'قریبی ورکرز ڈھونڈ رہے ہیں…',
    booked_view_job:      'لائیو سٹیٹس دیکھیں',

    reschedule_btn:         'وقت بدلیں',
    reschedule_title:       'بکنگ کا وقت بدلیں',
    reschedule_sub:         'نئی تاریخ اور آغاز کا وقت منتخب کریں۔ آپ کی ادائیگی اور تلاش جاری رہے گی۔',
    reschedule_date_label:  'نئی تاریخ',
    reschedule_start_label: 'نیا آغاز وقت',
    reschedule_end_label:   'نیا اختتام وقت (اختیاری)',
    reschedule_confirm:     'نیا شیڈول محفوظ کریں',
    reschedule_back:        'موجودہ شیڈول رکھیں',
    reschedule_submitting:  'محفوظ ہو رہا ہے…',
    reschedule_done:        'شیڈول اپ ڈیٹ ہو گیا',
    reschedule_failed:      'وقت نہیں بدل سکا۔ دوبارہ کوشش کریں۔',
    reschedule_or_cancel:   'یا منسوخ کریں اور ریفنڈ پائیں',
  },

  te: {
    greeting_morning:   'శుభోదయం',
    greeting_afternoon: 'నమస్కారం',
    greeting_evening:   'శుభ సాయంత్రం',
    today_money:        'నేటి సంపాదన',
    this_week:          'ఈ వారంలో',
    go_online:          'పని ప్రారంభించండి — ఆన్‌లైన్ అవ్వండి',
    you_are_online:     'మీరు ఆన్‌లైన్‌లో ఉన్నారు. ఇప్పుడు పని దొరకవచ్చు.',
    jobs_near_you:      'మీకు దగ్గరలో పనులు',
    see_all:            'అన్నీ చూడండి',
    view_apply:         'వివరాలు చూసి దరఖాస్తు చేయండి',
    filters:            ['అన్నీ','నేడు','రేపు','దగ్గర','అధిక వేతనం'],
    you_earn:           'మీకు వస్తుంది',
    spots_left:         (n:number) => `${n} స్థలాలు మిగిలాయి`,
    urgent:             '⚡ అర్జెంట్',
    apply_btn:          'ఈ పనికి దరఖాస్తు చేయండి →',
    applied_btn:        'అయింది! దరఖాస్తు చేయబడింది',
    home:               'హోమ్',
    browse:             'వెతకండి',
    shifts:             'షిఫ్ట్‌లు',
    earnings:           'సంపాదన',
    profile:            'ప్రొఫైల్',
    total_earned:       'మొత్తం సంపాదన (ఈ నెల)',
    in_your_bank:       'మీ బ్యాంకులో',
    on_the_way:         'వస్తోంది',
    this_week_lbl:      'ఈ వారంలో',
    payment_history:    'చెల్లింపు చరిత్ర',
    paid_lbl:           '✓ వచ్చింది',
    processing_lbl:     '⏳ వస్తోంది',
    my_shifts:          'నా షిఫ్ట్‌లు',
    upcoming:           '📅 రాబోయే',
    past_shifts:        '✅ గత',
    my_availability:    'నా అందుబాటు',
    tap_to_show:        'ఎప్పుడు పని చేయగలరో ట్యాప్ చేయండి',
    avail_set:          (n:number) => `${n} స్లాట్‌లు సెట్`,
    available:          'అందుబాటులో',
    not_available:      'అందుబాటులో లేదు',
    settings:           'సెట్టింగ్‌లు',
    notifications_lbl:  'నోటిఫికేషన్లు',
    all_lbl:            'అన్నీ',
    unread_lbl:         'చదవలేదు',
    no_notifs:          'ఇంకా నోటిఫికేషన్లు లేవు',
    confirm_job_ttl:    'పని దొరికింది!',
    confirm_job_sub:    'బాగు! మీ షిఫ్ట్ నిర్ధారించబడింది.',
    get_directions:     'దిశలు చూడండి',
    tell_friend:        'స్నేహితుడికి చెప్పండి',
    back_to_jobs:       'పనులకు తిరిగి వెళ్ళండి',
    slide_to_accept:    'అంగీకరించడానికి స్లైడ్ చేయండి →',
    urgent_nearby:      'దగ్గర అర్జెంట్',
    urgent_headline:    'యజమానికి ఇప్పుడే ఎవరైనా కావాలి — 1 గంటలో',
    urgent_spots_txt:   (dist:string, n:number) => `${dist} దూరంలో · కేవలం ${n} స్థలాలు మిగిలాయి`,
    accept_job:         'ఈ పనిని అంగీకరించండి',
    accept_job_sub:     'నిర్ధారించే ముందు పూర్తి వివరాలు చూడండి',
    not_interested:     'ఆసక్తి లేదు',
    enter_arrival_otp:  'రాక OTP నమోదు చేయండి',
    ask_employer_otp:   'యజమాని నుండి 6 అంకెల కోడ్ తీసుకోండి',
    starts_shift_timer: 'ఇది మీ షిఫ్ట్ టైమర్ ప్రారంభిస్తుంది',
    confirm_arrival:    'రాకను నిర్ధారించండి',
    shift_in_progress:  'షిఫ్ట్ జరుగుతోంది',
    earned_so_far:      'ఇప్పటివరకు సంపాదించారు',
    slide_to_end:       'షిఫ్ట్ ముగించడానికి స్లైడ్ చేయండి',
    slide_to_end_sub:   'షిఫ్ట్ పూర్తి చేయడానికి స్లైడ్ చేయండి',
    shift_ended:        'షిఫ్ట్ ముగిసింది!',
    accepted_lbl:       'అంగీకరించబడింది!',
    active_shift:       'చురుకైన షిఫ్ట్',
    confirm_arrival_ttl:'రాక నిర్ధారణ',
    wrong_otp:          'తప్పు OTP — మళ్ళీ ప్రయత్నించండి',
    demo_otp:           'డెమో OTP:',
    job_details:        'పని వివరాలు',
    what_to_bring:      'ఏమి తీసుకొచ్చాలి',
    money_note:         'షిఫ్ట్ తర్వాత నేరుగా మీ ఖాతాకు డబ్బు వస్తుంది',
    you_will_earn:      'మీకు వస్తుంది',
    what_bring_items:   ['చెల్లుబాటు అయ్యే గుర్తింపు కార్డ్','సౌకర్యవంతమైన బూట్లు','నీళ్ళ సీసా','మీ ఫోన్'],
    skills_title:       'నా నైపుణ్యాలు',
    skills_sub:         'మీరు ఏ పని చేయగలరో చెప్పండి',
    edit_info:          'సమాచారం మార్చండి',
    work_area:          'పని ప్రాంతం',
    languages_speak:    'నాకు వచ్చిన భాషలు',
    save_changes:       'సేవ్ చేయండి',
    search_placeholder: 'పనులు, కంపెనీలు వెతకండి...',
    no_jobs_found:      'పనులు కనుగొనబడలేదు',
    no_jobs_sub:        'వేరే శోధన లేదా వర్గాన్ని ప్రయత్నించండి',
    rate_job:           '⭐ ఈ పనిని రేట్ చేయండి',
    confirmed:          'నిర్ధారించబడింది',
    pending:            'పెండింగ్',
    completed:          'పూర్తయింది',
    jobs_done:          'పనులు చేశారు',
    your_rating:        'మీ రేటింగ్',
    money_coming:       'డబ్బు వస్తోంది',
    results:            'ఫలితాలు',
    all_jobs:           'అన్ని పనులు',
    date_when:          'ఎప్పుడు',
    duration:           'ఎంత సేపు',
    pay_lbl:            'వేతనం',
    distance:           'దూరం',
    slots:              'స్థలాలు',
    rating:             'రేటింగ్',
    onb1_title:         'దగ్గర పని కనుగొనండి',
    onb1_sub:           'ఇంటి నుండి 5 కి.మీ లోపల ధృవీకరించిన పనులు చూడండి.',
    onb2_title:         'గంటకు ₹99–₹129 సంపాదించండి',
    onb2_sub:           'స్థిర రేట్లు. ఏజెంట్ కట్ లేదు. దాచిన ఫీజు లేదు.',
    onb3_title:         'అదే రోజు డబ్బు పొందండి',
    onb3_sub:           'ప్రతి షిఫ్ట్ తర్వాత నేరుగా బ్యాంకుకు డబ్బు వెళ్తుంది.',
    onb4_title:         'సురక్షితమైన మరియు ధృవీకరించిన పనులు',
    onb4_sub:           'ప్రతి యజమాని తనిఖీ చేయబడ్డారు. ఆధార్ ద్వారా రక్షణ.',
    get_started:        'ప్రారంభించండి →',
    already_account:    'ఇప్పటికే ఖాతా ఉందా? లాగిన్ చేయండి',
    login_title:        'తిరిగి స్వాగతం',
    login_sub:          'కొనసాగించడానికి మీ నంబర్ నమోదు చేయండి',
    phone_label:        'మొబైల్ నంబర్',
    phone_placeholder:  '10 అంకెల నంబర్ నమోదు చేయండి',
    password_label:     'పాస్‌వర్డ్',
    password_placeholder:'పాస్‌వర్డ్ నమోదు చేయండి',
    login_btn:          'లాగిన్ చేయండి',
    no_account:         'ఖాతా లేదా? నమోదు చేసుకోండి',
    register_title:     'ఖాతా తయారు చేయండి',
    register_sub:       'వేల మంది కార్మికులతో కలిసి రోజువారీ సంపాదించండి',
    name_label:         'పూర్తి పేరు',
    name_placeholder:   'మీ పూర్తి పేరు నమోదు చేయండి',
    city_label:         'మీ నగరం',
    city_placeholder:   'ఉదా. హైదరాబాద్, విజయవాడ, విశాఖ',
    lang_label:         'యాప్ భాష',
    register_btn:       'ఖాతా తయారు చేయండి',
    have_account:       'ఇప్పటికే ఖాతా ఉందా? లాగిన్ చేయండి',
    choose_language:    'భాష ఎంచుకోండి',
    choose_language_sub:'మీకు అత్యంత సౌకర్యవంతమైన భాష ఎంచుకోండి',
    continue_btn:       'కొనసాగించండి',
    change_language:    'భాష మార్చండి',

    rate_worker_title:    'వర్కర్‌కి రేటింగ్ ఇవ్వండి',
    rate_worker_sub:      'మీ రేటింగ్ ప్లాట్‌ఫామ్ నాణ్యతను నిర్వహించడంలో సహాయపడుతుంది',
    rate_stars_label:     'నక్షత్రాలను ఎంచుకోండి',
    rate_review_ph:       'చిన్న రివ్యూ రాయండి (ఐచ్ఛికం)',
    rate_submit:          'రేటింగ్ పంపించు',
    rate_skip:            'దాటవేయి',
    rate_submitting:      'పంపిస్తున్నాం…',
    rate_thanks:          'మీ అభిప్రాయానికి ధన్యవాదాలు!',
    rate_failed:          'పంపలేకపోయాం. మళ్ళీ ప్రయత్నించండి.',

    cancel_shift_btn:     'రద్దు చేసి రీఫండ్ పొందండి',
    cancel_shift_title:   'ఈ బుకింగ్ రద్దు చేయాలా?',
    cancel_shift_sub:     'పూర్తి రీఫండ్ లభిస్తుంది. వర్కర్ అంగీకరించడానికి ముందు మాత్రమే ఇది అందుబాటులో ఉంది.',
    cancel_shift_reason_ph:'కారణం (ఐచ్ఛికం)',
    cancel_shift_confirm: 'అవును, రద్దు చేసి రీఫండ్ ఇవ్వండి',
    cancel_shift_back:    'బుకింగ్ ఉంచండి',
    cancel_shift_done:    'బుకింగ్ రద్దు · రీఫండ్ ప్రారంభం',
    cancel_shift_failed:  'రద్దు చేయలేకపోయాం. మళ్ళీ ప్రయత్నించండి.',

    booked_title:         'బుకింగ్ పూర్తయింది!',
    booked_sub:           'మేము సమీపంలోని వర్కర్‌లకు తెలియజేస్తున్నాం',
    booked_searching:     'సమీపంలోని వర్కర్‌లను వెతుకుతున్నాం…',
    booked_view_job:      'లైవ్ స్థితిని చూడండి',

    reschedule_btn:         'సమయం మార్చండి',
    reschedule_title:       'బుకింగ్ సమయం మార్చండి',
    reschedule_sub:         'కొత్త తేదీ మరియు ప్రారంభ సమయాన్ని ఎంచుకోండి. మీ చెల్లింపు మరియు వెతుకుతున్న వర్కర్ అలాగే ఉంటారు.',
    reschedule_date_label:  'కొత్త తేదీ',
    reschedule_start_label: 'కొత్త ప్రారంభ సమయం',
    reschedule_end_label:   'కొత్త ముగింపు సమయం (ఐచ్ఛికం)',
    reschedule_confirm:     'కొత్త షెడ్యూల్‌ను సేవ్ చేయండి',
    reschedule_back:        'ప్రస్తుత షెడ్యూల్‌ను ఉంచండి',
    reschedule_submitting:  'సేవ్ చేస్తున్నాం…',
    reschedule_done:        'షెడ్యూల్ అప్‌డేట్ అయింది',
    reschedule_failed:      'మార్చలేకపోయాం. మళ్ళీ ప్రయత్నించండి.',
    reschedule_or_cancel:   'లేదా రద్దు చేసి రీఫండ్ పొందండి',
  },
}

/* ── Context ──────────────────────────────────────────────────── */
const LangCtx = createContext<{
  lang: Lang
  t: typeof T['en']
  setLang: (l: Lang) => void
}>({ lang: 'en', t: T.en, setLang: () => {} })

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en')

  function applyDir(l: Lang) {
    const isRtl = LANGUAGES.find(x => x.code === l)?.dir === 'rtl'
    if (typeof document !== 'undefined') {
      document.documentElement.dir = isRtl ? 'rtl' : 'ltr'
    }
  }

  useEffect(() => {
    const saved = localStorage.getItem('sw_lang') as Lang | null
    if (saved && saved in T) { setLangState(saved as Lang); applyDir(saved as Lang) }
  }, [])

  function setLang(l: Lang) {
    setLangState(l)
    localStorage.setItem('sw_lang', l)
    applyDir(l)
  }

  return (
    <LangCtx.Provider value={{ lang, t: T[lang], setLang }}>
      {children}
    </LangCtx.Provider>
  )
}

export const useLang = () => useContext(LangCtx)
